---

- hosts: centos
  tasks:
  - name: Delete a user
    user:
      name: weblogic
      state: absent
      remove: yes
  - name: Delete group finance
    group:
      name: finance
      state: absent
  - name: Delete a directory
    file:
      path: /opt/oracle/
      state: absent
  - name: Remove user consultant
    user:
      name: consultant
      state: absent
      remove: yes
  - name: Remove user supervisor
    user:
      name: supervisor
      state: absent
      remove: yes

